/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2019-09-17 17:35:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<script language = \"javascript\">\n");
      out.write("\n");
      out.write("function writeCheck()\n");
      out.write("{\n");
      out.write("\tvar form = document.writeform;\n");
      out.write("\t\n");
      out.write("\tif(!form.proname.value)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"제품 명을 선택하세요.\");\n");
      out.write("\t\tform.name.focus();\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tif(!form.proloc.value)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"생산지를 적어주세요.\");\n");
      out.write("\t\tform.proloc.focus();\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\tif(!form.pronumber.value)\n");
      out.write("\t{\n");
      out.write("\t\talert(\"개수를 입력하세요.\");\n");
      out.write("\t\tform.pronumber.focus();\n");
      out.write("\t\treturn;\n");
      out.write("\t}\n");
      out.write("\tform.submit();\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write(" \t\t<title> 공산품 관리 </title>\n");
      out.write("\t</head>\n");
      out.write(" \t<body>\n");
      out.write(" \t\t<table>\n");
      out.write("\t\t\t <center>\n");
      out.write("\t\t\t\t <form name=writeform method=post action=\"write_ok.jsp\">\n");
      out.write("\t\t\t\t \t\t\t<br /><br /><br /><br /><br /><br /><br /><br /><br />\n");
      out.write("<!-- \t\t\t\t \t\t\t제품 명 : <input name=\"proname\" placeholder=\"공산품 제품명\"/>\n");
      out.write("\t\t\t\t \t\t\t생산지 : \t<input name=\"proloc\" placeholder=\"생산지\" />\n");
      out.write("\t\t\t\t\t\t\t개수 : \t<input name=\"pronumber\" placeholder=\"공산품 개수\"/> -->\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<!-- 제품 명 : <select name=\"proname\" size=\"1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected disabled hidden> 제품 명을 선택하세요.</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"AIR JORDAN 1\">AIR JORDAN 1</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"YEEZY BOOST\">YEEZY BOOST</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t제품 명 : <input autocomplete=off list=\"product\" name=\"proname\" placeholder=\"공산품 제품 명\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<datalist id=\"product\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"AIR JORDAN1\">AIR JORDAN1</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"YEEZY BOOST\">YEEZY BOOST</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</datalist>\n");
      out.write("\t\t\t\t\t\t\t생산지 : \t<!-- <input autocomplete=off name=\"proloc\" placeholder=\"생산지\" /> -->\n");
      out.write("\t\t\t\t\t\t\t\t\t<select name=\"proloc\" size=1\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<optgroup label=\"ASIA\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\" selected disabled hidden> 생산지를 선택하세요.</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"KR\">KR(KOREA)</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"CH\">CH(CHINA)</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</optgroup>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t개수 : \t<input autocomplete=off name=\"pronumber\" placeholder=\"공산품 개수\"/>\n");
      out.write("\t\t\t\t </form>\n");
      out.write("\t\t\t </center>\n");
      out.write("\t\t</table>\n");
      out.write(" \n");
      out.write("\t\t<table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\">\n");
      out.write("  \t\t<tr>\n");
      out.write("  \t\t\t<td colspan=\"4\" height=\"5\"></td>\n");
      out.write("  \t\t</tr>\n");
      out.write("  \t\t<tr align=\"center\">\n");
      out.write("   \t\t\t<td>\n");
      out.write("   \t\t\t\t<input type=button value=\"등록\" OnClick = \"javascript:writeCheck();\">\n");
      out.write("   \t\t\t</td>\n");
      out.write("  \t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("\t</body> \n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
